#ifndef VHTML_H
#define VHTML_H

// ----------- Allocation -------------

// Choose your Own
#ifndef VHTML_ALLOC
	#include <stdlib.h>
	#define VHTML_MALLOC malloc
	#define VHTML_FREE free
	#define VHTML_CALLOC calloc
	#define VHTML_REALLOC realloc
#endif

struct VHTMLArenaChunk {
	unsigned char *data;
	size_t used;
	size_t size;
	struct VHTMLArenaChunk *next;
};

typedef struct VHTMLArena {
	struct VHTMLArenaChunk *head;
	struct VHTMLArenaChunk *tail;
} VHTMLArena;

VHTMLArena *arena_init(size_t size);
void arena_reset(VHTMLArena *arena);
void arena_free(VHTMLArena *arena);

// ----------- END: Allocation -------------

// 4/28/26
// _TYPE_COUNT should stay at the last element for indexing into
// https://html.spec.whatwg.org/multipage/indices.html#attributes-3
typedef enum {
	VHTMLTAG_DOCTYPE,
	VHTMLTAG_HTML, VHTMLTAG_BASE, VHTMLTAG_HEAD, VHTMLTAG_LINK, VHTMLTAG_META, VHTMLTAG_STYLE,
	VHTMLTAG_TITLE, VHTMLTAG_BODY, VHTMLTAG_ADDRESS, VHTMLTAG_ARTICLE, VHTMLTAG_ASIDE,
	VHTMLTAG_FOOTER, VHTMLTAG_HEADER, VHTMLTAG_H1, VHTMLTAG_H2, VHTMLTAG_H3, VHTMLTAG_H4,
	VHTMLTAG_H5, VHTMLTAG_H6, VHTMLTAG_HGROUP, VHTMLTAG_MAIN, VHTMLTAG_NAV, VHTMLTAG_SECTION,
	VHTMLTAG_SEARCH, VHTMLTAG_BLOCKQUOTE, VHTMLTAG_DD, VHTMLTAG_DIV, VHTMLTAG_DL,
	VHTMLTAG_DT, VHTMLTAG_FIGCAPTION, VHTMLTAG_FIGURE, VHTMLTAG_HR, VHTMLTAG_LI, VHTMLTAG_MENU,
	VHTMLTAG_OL, VHTMLTAG_P, VHTMLTAG_PRE, VHTMLTAG_UL, VHTMLTAG_A, VHTMLTAG_ABBR, VHTMLTAG_B, VHTMLTAG_BDI, VHTMLTAG_BDO,
	VHTMLTAG_BR, VHTMLTAG_CITE, VHTMLTAG_CODE, VHTMLTAG_DATA, VHTMLTAG_DFN, VHTMLTAG_EM, VHTMLTAG_I, VHTMLTAG_KBD,
	VHTMLTAG_MARK, VHTMLTAG_G, VHTMLTAG_RP, VHTMLTAG_RT, VHTMLTAG_RUBY, VHTMLTAG_S, VHTMLTAG_SAMP, VHTMLTAG_SMALL,
	VHTMLTAG_SPAN, VHTMLTAG_STRONG, VHTMLTAG_SUB, VHTMLTAG_SUP, VHTMLTAG_TIME, VHTMLTAG_U, VHTMLTAG_VAR, VHTMLTAG_WBR,
	VHTMLTAG_AREA, VHTMLTAG_AUDIO, VHTMLTAG_IMG, VHTMLTAG_MAP, VHTMLTAG_TRACK, VHTMLTAG_VIDEO,
	VHTMLTAG_EMBED, VHTMLTAG_FENCEDFRAME, VHTMLTAG_IFRAME, VHTMLTAG_OBJECT,
	VHTMLTAG_PICTURE, VHTMLTAG_SOURCE, VHTMLTAG_SVG, VHTMLTAG_MATH, VHTMLTAG_CANVAS, VHTMLTAG_NOSCRIPT,
	VHTMLTAG_SCRIPT, VHTMLTAG_DEL, VHTMLTAG_INS, VHTMLTAG_CAPTION, VHTMLTAG_COL, VHTMLTAG_COLGROUP,
	VHTMLTAG_TABLE, VHTMLTAG_TBODY, VHTMLTAG_TD, VHTMLTAG_TFOOT, VHTMLTAG_TH, VHTMLTAG_THEAD, VHTMLTAG_TR,
	VHTMLTAG_BUTTON, VHTMLTAG_DATALIST, VHTMLTAG_FIELDSET, VHTMLTAG_FORM, VHTMLTAG_INPUT,
	VHTMLTAG_LABEL, VHTMLTAG_LEGEND, VHTMLTAG_METER, VHTMLTAG_OPTGROUP, VHTMLTAG_OPTION,
	VHTMLTAG_OUTPUT, VHTMLTAG_PROGRESS, VHTMLTAG_SELECT, VHTMLTAG_SELECTEDCONTENT,
	VHTMLTAG_TEXTAREA, VHTMLTAG_DETAILS, VHTMLTAG_DIALOG, VHTMLTAG_GEOLOCATION,
	VHTMLTAG_SUMMARY, VHTMLTAG_SLOT, VHTMLTAG_TEMPLATE, VHTMLTAG_ACRONYM, VHTMLTAG_BIG, VHTMLTAG_CENTER,
	VHTMLTAG_CONTENT, VHTMLTAG_DIR, VHTMLTAG_FONT, VHTMLTAG_FRAME, VHTMLTAG_FRAMESET, VHTMLTAG_IMAGE,
	VHTMLTAG_MARQUEE, VHTMLTAG_MENUITEM, VHTMLTAG_NOBR, VHTMLTAG_NOEMBED, VHTMLTAG_NOFRAMES,
	VHTMLTAG_PARAM, VHTMLTAG_PLAINTEXT, VHTMLTAG_RB, VHTMLTAG_RTC, VHTMLTAG_SHADOW, VHTMLTAG_STRIKE, VHTMLTAG_TT,
	VHTMLTAG_XMP,
	
	VHTMLTAG_CUSTOM, _VHTMLTAG_TEXT,
	_VHTMLTAG_ROOT,
	_VHTML_TAG_COUNT
} VHTMLTag_t;

struct VHTMLTag_st {
	const char *tag_name;
	VHTMLTag_t ident;
};

struct VHTMLTag_st *lookup_htmltag (register const char *str, register size_t len);

typedef enum {
	VHTMLATTR_ACCEPT, VHTMLATTR_ACCEPTCHARSET, VHTMLATTR_ACCESSKEY, VHTMLATTR_ACTION, VHTMLATTR_ALIGN,
	VHTMLATTR_ALT, VHTMLATTR_ASYNC, VHTMLATTR_AUTOCOMPLETE, VHTMLATTR_AUTOFOCUS, VHTMLATTR_AUTOPLAY,
	VHTMLATTR_BGCOLOR, VHTMLATTR_BORDER, VHTMLATTR_CHARSET, VHTMLATTR_CHECKED, VHTMLATTR_CITE, VHTMLATTR_CLASS,
	VHTMLATTR_COLOR, VHTMLATTR_COLS, VHTMLATTR_COLSPAN, VHTMLATTR_CONTENT, VHTMLATTR_CONTENTEDITABLE,
	VHTMLATTR_CONTROLS, VHTMLATTR_COORDS, VHTMLATTR_DATA, VHTMLATTR_DATETIME, VHTMLATTR_DEFAULT, VHTMLATTR_DEFER,
	VHTMLATTR_DIR, VHTMLATTR_DIRNAME, VHTMLATTR_DISABLED, VHTMLATTR_DOWNLOAD, VHTMLATTR_DRAGGABLE, VHTMLATTR_ENCTYPE,
	VHTMLATTR_ENTERKEYHINT, VHTMLATTR_FOR, VHTMLATTR_FORM, VHTMLATTR_FORMACTION, VHTMLATTR_HEADERS, VHTMLATTR_HEIGHT,
	VHTMLATTR_HIDDEN, VHTMLATTR_HIGH, VHTMLATTR_HREF, VHTMLATTR_HREFLANG, VHTMLATTR_HTTPEQUIV, VHTMLATTR_ID, VHTMLATTR_INERT,
	VHTMLATTR_INPUTMODE, VHTMLATTR_ISMAP, VHTMLATTR_KIND, VHTMLATTR_LABEL, VHTMLATTR_LANG, VHTMLATTR_LIST, VHTMLATTR_LOOP, VHTMLATTR_LOW,
	VHTMLATTR_MAX, VHTMLATTR_MAXLENGTH, VHTMLATTR_MEDIA, VHTMLATTR_METHOD, VHTMLATTR_MIN, VHTMLATTR_MULTIPLE, VHTMLATTR_MUTED,
	VHTMLATTR_NAME, VHTMLATTR_NOVALIDATE, VHTMLATTR_ONABORT, VHTMLATTR_ONAFTERPRINT, VHTMLATTR_ONBEFOREPRINT,
	VHTMLATTR_ONBEFOREUNLOAD, VHTMLATTR_ONBLUR, VHTMLATTR_ONCANPLAY, VHTMLATTR_ONCANPLAYTHROUGH,
	VHTMLATTR_ONCHANGE, VHTMLATTR_ONCLICK, VHTMLATTR_ONCONTEXTMENU, VHTMLATTR_ONCOPY, VHTMLATTR_ONCUECHANGE,
	VHTMLATTR_ONCUT, VHTMLATTR_ONDBLCLICK, VHTMLATTR_ONDRAG, VHTMLATTR_ONDRAGEND, VHTMLATTR_ONDRAGENTER,
	VHTMLATTR_ONDRAGLEAVE, VHTMLATTR_ONDRAGOVER, VHTMLATTR_ONDRAGSTART, VHTMLATTR_ONDROP, VHTMLATTR_ONDURATIONCHANGE,
	VHTMLATTR_ONEMPTIED, VHTMLATTR_ONENDED, VHTMLATTR_ONERROR, VHTMLATTR_ONFOCUS, VHTMLATTR_ONHASCHANGE,
	VHTMLATTR_ONINPUT, VHTMLATTR_ONINVALID, VHTMLATTR_ONKEYDOWN, VHTMLATTR_ONKEYPRESS, VHTMLATTR_ONKEYUP, VHTMLATTR_ONLOAD,
	VHTMLATTR_ONLOADEDDATA, VHTMLATTR_ONLOADEDMETADATA, VHTMLATTR_ONLOADSTART, VHTMLATTR_ONMOUSEDOWN,
	VHTMLATTR_ONMOUSEMOVE, VHTMLATTR_ONMOUSEOUT, VHTMLATTR_ONMOUSEOVER, VHTMLATTR_ONMOUSEUP,
	VHTMLATTR_ONMOUSEWHEEL, VHTMLATTR_ONOFFLINE, VHTMLATTR_ONONLINE, VHTMLATTR_ONPAGEHIDE, VHTMLATTR_ONPAGESHOW,
	VHTMLATTR_ONPASTE, VHTMLATTR_ONPAUSE, VHTMLATTR_ONPLAY, VHTMLATTR_ONPLAYING, VHTMLATTR_ONPOPSTATE, VHTMLATTR_ONPROGRESS,
	VHTMLATTR_ONRATECHANGE, VHTMLATTR_ONRESET, VHTMLATTR_ONRESIZE, VHTMLATTR_ONSCROLL, VHTMLATTR_ONSEARCH, VHTMLATTR_ONSEEKED,
	VHTMLATTR_ONSEEKING, VHTMLATTR_ONSELECT, VHTMLATTR_ONSTALLED, VHTMLATTR_ONSTORAGE, VHTMLATTR_ONSUBMIT,
	VHTMLATTR_ONSUSPEND, VHTMLATTR_ONTIMEUPDATE, VHTMLATTR_ONTOGGLE, VHTMLATTR_ONUNLOAD, VHTMLATTR_ONVOLUMECHANGE,
	VHTMLATTR_ONWAITING, VHTMLATTR_ONWHEEL, VHTMLATTR_OPEN, VHTMLATTR_OPTIMUM, VHTMLATTR_PATTERN, VHTMLATTR_PLACEHOLDER, VHTMLATTR_POPOVER,
	VHTMLATTR_POPOVERTARGET, VHTMLATTR_POPOVERTARGETACTION, VHTMLATTR_POSTER, VHTMLATTR_PRELOAD, VHTMLATTR_READONLY, VHTMLATTR_REL,
	VHTMLATTR_REQUIRED, VHTMLATTR_REVERSED, VHTMLATTR_ROWS, VHTMLATTR_ROWSPAN, VHTMLATTR_SANDBOX, VHTMLATTR_SCOPE, VHTMLATTR_SELECTED,
	VHTMLATTR_SHAPE, VHTMLATTR_SIZE, VHTMLATTR_SIZES, VHTMLATTR_SPAN, VHTMLATTR_SPELLCHECK, VHTMLATTR_SRC, VHTMLATTR_SRCDOC, VHTMLATTR_SRCLANG,
	VHTMLATTR_SRCSET, VHTMLATTR_START, VHTMLATTR_STEP, VHTMLATTR_STYLE, VHTMLATTR_TABINDEX, VHTMLATTR_TARGET, VHTMLATTR_TITLE, VHTMLATTR_TRANSLATE,
	VHTMLATTR_TYPE, VHTMLATTR_USEMAP, VHTMLATTR_VALUE, VHTMLATTR_WIDTH, VHTMLATTR_WRAP,

	VHTMLATTR_XMLNS, VHTMLATTR_XMLNS_XLINK,

	VHTMLATTR_DATA_CUST, VHTMLATTR_HTML,
	_VHTML_ATTRIBUTE_COUNT
} VHTMLAttribute_t;

struct VHTMLAttribute_st {
	const char *attr_name;
	VHTMLAttribute_t ident;
};

struct VHTMLAttribute_st *lookup_htmlattr (register const char *str, register size_t len);

// 4 types of attributes, data- namespaced: defined, and unknown
typedef struct VHTMLDataAttribute {
	char *name;
	char *value;
	char quoted;
	struct VHTMLDataAttribute *next;
} VHTMLDataAttribute;

typedef enum VHTMLNamespace {
	VHTMLNS_XML,
	VHTMLNS_XLINK
} VHTMLNamespace;

typedef struct VHTMLNamespacedAttribute {
	VHTMLNamespace ns;
	char *name;
	char quoted;
	char *value;
	struct VHTMLNamespacedAttribute *next;
} VHTMLNamespacedAttribute;

typedef struct VHTMLAttribute {
	VHTMLAttribute_t type;
	char quoted;
	char *value;
	struct VHTMLAttribute *next;
} VHTMLAttribute;

typedef struct VHTMLUnknownAttribute {
	char *name;
	char quoted;
	char *value;
	struct VHTMLUnknownAttribute *next;
} VHTMLUnknownAttribute;

// ------ END: Attributes -------

typedef struct VHTMLNode {
	VHTMLTag_t type;
	char *_text;
	struct VHTMLNode *children;					// Linked-List head of children in order
	struct VHTMLNode *last_child;				// End of children linked-list
	struct VHTMLNode *parent;
	struct VHTMLAttribute *attributes;			// Linked-List of defined HTML attributes
	struct VHTMLDataAttribute *data_attrs;		// data-* attributes
	struct VHTMLNamespacedAttribute *ns_attrs;	// Namespaced attributes
	struct VHTMLUnknownAttribute *unk_attrs;	// Unknown attributes are allowed by HTML5 spec
	struct VHTMLNode *_next_sib;				// Used for linked list
} VHTMLNode;

typedef struct VHTMLDocument {
	VHTMLNode *root;
	VHTMLArena *allocation;
	char *raw_buf;
	int owns_allocations;
	VHTMLNode *body;
} VHTMLDocument;

// Index into this using a VHTMLTAG_* enum to get a string representation
// of that value
extern const char *const html_element_str[];
// Index into this using a VHTMLATTR_* enum to get a string representation
// of that value
extern const char *const html_attribute_str[];

VHTMLNode* create_element_t(VHTMLTag_t type, VHTMLArena *arena);
VHTMLNode* create_element(char *name, VHTMLArena *arena);

/*
 * Destructively parses `buf` into a node allocated to `arena`
 *
 * @param parent - if parent is not NULL, parent becomes the stack sentinel
 *	and the first open tag is treated as the child of it
 * */
VHTMLNode* parse_node(char *buf, VHTMLNode *parent, VHTMLArena *arena);

// Sets an attribute to some heap/arena allocated value for some node, 0 implying a
// boolean attribute's existence. Thus, it may be undone with the unset_attr function
VHTMLAttribute* set_attr(VHTMLNode *node, VHTMLAttribute_t attribute, char *value, VHTMLArena *arena);
void unset_attr(VHTMLNode *node, VHTMLAttribute_t attribute);
char* get_attr(VHTMLNode *node, VHTMLAttribute_t attribute);

/* 
 * Nondestructively parses a string into a DOM tree, returning a pointer to the heap allocated document struct.
 * It is important to note that if `arena` is NULL, the document will allocate an arena itsself of size FIXME bytes
 * which would need to be freed by caller to avoid leaks.
 *
 * If no string is provided, the document is created with the standard:
 * ```html
 * <!DOCTYPE html>
 * <html>
 *	<head></head>
 *	<body></body>
 * </html>
 * ```
 * */
VHTMLDocument* create_document(char *str, VHTMLArena *arena);

void free_document(VHTMLDocument *doc);

enum VHTMLPrintFormat {
	VHTMLPRINT_DEBUG,
	VHTMLPRINT_PRETTY,
	VHTMLPRINT_COMPACT
};

void printNode(VHTMLNode *node, enum VHTMLPrintFormat fmt);
char *serializeNode(VHTMLNode *node, enum VHTMLPrintFormat fmt);


VHTMLNode *append_child(VHTMLNode *parent, VHTMLNode *child);

/* This Library assumes that all strings are owned by the same arena as the
 * parent node because parsing is destrcutive. If instead direct memory management
 * is required, call the function twice, with `arena` set to NULL the first time
 * to indicate that the string pointer will remain valid for lifetime of the parent
 * node.
 */
VHTMLNode *set_inner_html(VHTMLNode *parent, char *str, VHTMLArena *arena);
VHTMLNode *set_inner_text(VHTMLNode *parent, char *str, VHTMLArena *arena);

// Returns heap-allocated buffer of all text in children
char *get_text_content(VHTMLNode *node, VHTMLArena *arena);

char *serializeDocument(VHTMLDocument *doc, enum VHTMLPrintFormat fmt);
#endif
